version: "3"

services:
    db:
        container_name: docker_mysql
        image: mysql:8.1.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - docker_symfony_network

    phpmyadmin:
        depends_on:
            - db
        container_name: docker_phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "9001:80"
        environment:
            - PMA_HOST=docker_mysql
            - PMA_PORT=3306
            - PMA_USER=root
            - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            - docker_symfony_network
    php:
        container_name: docker_php
        build:
            context: ./php
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ../:/var/www/symfony:cached
        networks:
            - docker_symfony_network
    nginx:
        container_name: docker_nginx
        build:
            context: ./nginx
        volumes:
            - ../:/var/www/symfony:cached
        ports:
            - 80:80
        networks:
            - docker_symfony_network
        env_file:
            - .env.nginx.local

    rabbitmq:
        container_name: docker_rabbitmq
        image: rabbitmq:management
        environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
        ports:
            - "15672:15672"
            - "5672:5672"
        networks:
            - docker_symfony_network

    redis:
        container_name: docker_redis
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
            - docker_symfony_network

volumes:
    db_data:

networks:
    docker_symfony_network:
        driver: bridge
